version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres_crud_ti
    environment:
      POSTGRES_DB: ${DB_NAME:-inventariodb}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
